services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
    ports:
      - 5000:5000

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    ports:
      - 5601:5601