auth_enabled: false
server:
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1

  storage:
    filesystem:
      chunks_directory: /etc/loki/loki-data
      rules_directory: /etc/loki/loki-rules


  ring:
    kvstore:
      store: memberlist

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/loki-ruler